version: '3.4'

services:
  redis:
    container_name: "redis"
    image: "redis/redis-stack-server"
    ports:
      - 6379:6379
  redis.dotnet.examples.queryparams:
    container_name: "redis.dotnet.examples.queryparams"
    image: ${DOCKER_REGISTRY-}redisdotnetexamples
    build:
      context: .
      dockerfile: src/Redis.DotNet.Examples.QueryParams/Dockerfile
    links:
      - redis
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:443;http://+:80
        REDIS_HOST: redis
        REDIS_PORT: 6379
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro